services:
  - type: web
    name: resume-matching
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host=0.0.0.0 --port=8000
    envVars:
      - key: RELEVANCE_AI_API_KEY
        sync: false
